name: .Razor Runtime Build & Unit tests

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-dotnet-unit-tests:
    name: .NET Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Restore dotnet dependencies
        run: dotnet restore
      - name: Build dotnet solution
        run: dotnet build --no-restore
      - name: Run dotnet unit tests
        run: dotnet test --no-build